services:
  web:
    restart: unless-stopped
    image: localhost/projectsend:latest
    build:
      context: .
      dockerfile: Dockerfile.ubi
    env_file: projectsend_env
    healthcheck:
      # PHP official image
      #test: curl --silent --output /dev/null --fail --user-agent "Docker HealthCheck" "http://127.0.0.1" || exit 1
      # PHP UBI image
      test: curl --silent --output /dev/null --fail --user-agent "Docker HealthCheck" "http://127.0.0.1:8080" || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      # PHP official image
      #- /srv/projectsend/config:/config
      #- /srv/projectsend/data:/data
      # PHP UBI image
      - /srv/projectsend/config:/opt/app-root/src/container_rw/config
      - /srv/projectsend/data:/opt/app-root/src/container_rw/data
    ports:
      # PHP official image
      # - "8081:80"
      # PHP UBI image
      - "8081:8080"

  mariadb:
    restart: unless-stopped
    image: docker.io/library/mariadb:lts-ubi
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - /srv/projectsend/db:/var/lib/mysql
    env_file: db_env
    environment:
      TZ: America/Sao_Paulo
