services:
  web:
    restart: unless-stopped
    image: localhost/projectsend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: projectsend_env
    volumes:
      - /srv/projectsend/config:/config
      - /srv/projectsend/data:/data
    ports:
      - "8081:80"

  mariadb:
    restart: unless-stopped
    image: docker.io/library/mariadb:lts-ubi
    volumes:
      - /srv/projectsend/db:/var/lib/mysql
    env_file: db_env
    environment:
      TZ: America/Sao_Paulo
